<?php
/**
 * Plugin Name: Test Test
 * Description: Block Editor plugin generated by create-block-plugin – build step required.
 * Version: 1.0.0
 * Plugin URI: https://wordpress.org/plugins/
 * Author: The WordPress Contributors
 * Author URI: https://wordpress.org/
 * Domain Path: /languages
 * License: GPL-2.0-or-later
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 * Tested up to: 5.4
 * Requires at least: 5.0
 * Requires PHP: 5.6
 * Text Domain: test-test
 *
 * @package TestTest
 */

namespace TestTest;

require __DIR__ . '/vendor/autoload.php';

if ( ! class_exists( 'Plugin' ) ) :
	/**
	 * Plugin Class.
	 *
	 * @since 1.0.0
	 */
	class Plugin {

		/**
		 * Class instance.
		 *
		 * @var Plugin
		 */
		private static $instance = null;

		/**
		 * Plugin Path.
		 *
		 * @var string
		 */
		public $plugin_dir_path;

		/**
		 * Plugin URL.
		 *
		 * @var string
		 */
		public $plugin_dir_url;

		/**
		 * Plugin slug.
		 *
		 * @var string
		 */
		public $slug;

		/**
		 * Plugin slug_snake_case.
		 *
		 * @var string
		 */
		public $slug_snake_case;

		/**
		 * Plugin textdomain.
		 *
		 * @var string
		 */
		public $textdomain;

		/**
		 * Plugin version.
		 *
		 * @var string
		 */
		public $version;

		/**
		 * Plugin constructor.
		 * Called immediately when you instantiate a class.
		 * Really good article on setting up constructors for WP classes.
		 * https://carlalexander.ca/designing-class-wordpress-hooks/
		 */
		private function __construct() {
			// filesystem directory i.e. /var/home/www/blockhandbook/wp-content/plugins/.
			$this->plugin_dir_path = plugin_dir_path( __FILE__ );
			// web address w/ trailing slash.
			// i.e. - http://blockhandbook.com/wp-content/plugins/.
			$this->plugin_dir_url  = plugin_dir_url( __FILE__ );
			$this->slug            = 'test-test';
			$this->slug_snake_case = 'test_test';
			$this->textdomain      = 'test-test';
			$this->version         = '1.0.0';
		}

		/**
		 * Return Plugin Instance.
		 *
		 * @return object\Plugin
		 */
		public static function get_instance() {
			if ( null === self::$instance ) {
				self::$instance = new self();
			}

			return self::$instance;
		}

		/**
		 * Load the plugin.
		 *
		 * @return void
		 */
		public static function load() {

			// You can find these classes in the includes/ directory.
			Load_Translations::register();
			Enqueue_Assets::register();
			Register_Blocks::register();
			Register_Plugin_Settings::register();
			Register_Rest_API::register();
			Register_Block_Patterns::register();
			Register_Testimonial_Custom_Post_Type::register();
			Register_Team_Custom_Post_Type::register();

			// Loop through and load dynamic block php files.
			// glob() function searches for all pathnames matching the pattern.
			foreach ( glob( __DIR__ . '/src/blocks/*/class-*.php' ) as $dynamic_block ) {
				require_once $dynamic_block;
			};
		}
	}
endif;

Plugin::load();
